// This file is auto-generated by util/generate_components.py
// Do not edit by hand.

import { MiniWebEcsChunkTableLayout, MiniWebEcsQueryChunkLayout } from "./ecs_c_api_gen.js";

export const ComponentIds = {
	"Alive": 0,
	"AssetReference": 1,
	"BoxCollision": 2,
	"Camera": 3,
	"CapsuleCollision": 4,
	"ConstraintDistance": 5,
	"ConstraintFixed": 6,
	"ConstraintHinge": 7,
	"ConstraintPoint": 8,
	"ConstraintSlider": 9,
	"ConstraintSwingTwist": 10,
	"DirectionalLight": 11,
	"DirectionalLightSettings": 12,
	"DoNotSerialize": 13,
	"EntityMetadata": 14,
	"EnvironmentSettings": 15,
	"Gizmo": 16,
	"Hierarchy": 17,
	"MainCamera": 18,
	"MeshCollision": 19,
	"MeshRenderer": 20,
	"PostProcessSettings": 21,
	"RigidBody": 22,
	"Root": 23,
	"Selected": 24,
	"SkeletonAnimation": 25,
	"SphereCollision": 26,
	"Text": 27,
	"Transform": 28,
	"WaterSettings": 29,
};

export const Alive = {
	name: "Alive",
	id: 0,
	typeId: 0,
	size: 0,
	byteSize: 0,
	fields: {
	},
	read(view, byteOffset) {
		return {};
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
	},
};

export const AssetReference = {
	name: "AssetReference",
	id: 1,
	typeId: 1,
	size: 8,
	byteSize: 8,
	alignment: 4,
	fields: {
		"asset_index": { offset: 0, type: "u32" },
		"asset_name_hash": { offset: 4, type: "u32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["asset_index"] = view.getUint32(byteOffset + 0, true);
		out["asset_name_hash"] = view.getUint32(byteOffset + 4, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["asset_index"] !== undefined) {
		view.setUint32(byteOffset + 0, value["asset_index"], true);
		}
		if (value["asset_name_hash"] !== undefined) {
		view.setUint32(byteOffset + 4, value["asset_name_hash"], true);
		}
	},
};

export const BoxCollision = {
	name: "BoxCollision",
	id: 2,
	typeId: 2,
	size: 12,
	byteSize: 12,
	alignment: 4,
	fields: {
		"half_extents": { offset: 0, type: "f32x3" },
	},
	read(view, byteOffset) {
		const out = {};
		out["half_extents"] = { x: view.getFloat32(byteOffset + 0, true), y: view.getFloat32(byteOffset + 4, true), z: view.getFloat32(byteOffset + 8, true) };
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		const fieldValue0 = value["half_extents"];
		if (fieldValue0 != null) {
			if (fieldValue0.x !== undefined) {
			view.setFloat32(byteOffset + 0, fieldValue0.x, true);
			}
			if (fieldValue0.y !== undefined) {
			view.setFloat32(byteOffset + 4, fieldValue0.y, true);
			}
			if (fieldValue0.z !== undefined) {
			view.setFloat32(byteOffset + 8, fieldValue0.z, true);
			}
		}
	},
};

export const Camera = {
	name: "Camera",
	id: 3,
	typeId: 3,
	size: 12,
	byteSize: 12,
	alignment: 4,
	fields: {
		"fov": { offset: 0, type: "f32" },
		"near": { offset: 4, type: "f32" },
		"far": { offset: 8, type: "f32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["fov"] = view.getFloat32(byteOffset + 0, true);
		out["near"] = view.getFloat32(byteOffset + 4, true);
		out["far"] = view.getFloat32(byteOffset + 8, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["fov"] !== undefined) {
		view.setFloat32(byteOffset + 0, value["fov"], true);
		}
		if (value["near"] !== undefined) {
		view.setFloat32(byteOffset + 4, value["near"], true);
		}
		if (value["far"] !== undefined) {
		view.setFloat32(byteOffset + 8, value["far"], true);
		}
	},
};

export const CapsuleCollision = {
	name: "CapsuleCollision",
	id: 4,
	typeId: 4,
	size: 8,
	byteSize: 8,
	alignment: 4,
	fields: {
		"radius": { offset: 0, type: "f32" },
		"half_height": { offset: 4, type: "f32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["radius"] = view.getFloat32(byteOffset + 0, true);
		out["half_height"] = view.getFloat32(byteOffset + 4, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["radius"] !== undefined) {
		view.setFloat32(byteOffset + 0, value["radius"], true);
		}
		if (value["half_height"] !== undefined) {
		view.setFloat32(byteOffset + 4, value["half_height"], true);
		}
	},
};

export const ConstraintDistance = {
	name: "ConstraintDistance",
	id: 5,
	typeId: 5,
	size: 40,
	byteSize: 40,
	alignment: 4,
	fields: {
		"entity_a": { offset: 0, type: "u32" },
		"entity_b": { offset: 4, type: "u32" },
		"anchor_a": { offset: 8, type: "f32x3" },
		"anchor_b": { offset: 20, type: "f32x3" },
		"min_distance": { offset: 32, type: "f32" },
		"max_distance": { offset: 36, type: "f32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["entity_a"] = view.getUint32(byteOffset + 0, true);
		out["entity_b"] = view.getUint32(byteOffset + 4, true);
		out["anchor_a"] = { x: view.getFloat32(byteOffset + 8, true), y: view.getFloat32(byteOffset + 12, true), z: view.getFloat32(byteOffset + 16, true) };
		out["anchor_b"] = { x: view.getFloat32(byteOffset + 20, true), y: view.getFloat32(byteOffset + 24, true), z: view.getFloat32(byteOffset + 28, true) };
		out["min_distance"] = view.getFloat32(byteOffset + 32, true);
		out["max_distance"] = view.getFloat32(byteOffset + 36, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["entity_a"] !== undefined) {
		view.setUint32(byteOffset + 0, value["entity_a"], true);
		}
		if (value["entity_b"] !== undefined) {
		view.setUint32(byteOffset + 4, value["entity_b"], true);
		}
		const fieldValue2 = value["anchor_a"];
		if (fieldValue2 != null) {
			if (fieldValue2.x !== undefined) {
			view.setFloat32(byteOffset + 8, fieldValue2.x, true);
			}
			if (fieldValue2.y !== undefined) {
			view.setFloat32(byteOffset + 12, fieldValue2.y, true);
			}
			if (fieldValue2.z !== undefined) {
			view.setFloat32(byteOffset + 16, fieldValue2.z, true);
			}
		}
		const fieldValue3 = value["anchor_b"];
		if (fieldValue3 != null) {
			if (fieldValue3.x !== undefined) {
			view.setFloat32(byteOffset + 20, fieldValue3.x, true);
			}
			if (fieldValue3.y !== undefined) {
			view.setFloat32(byteOffset + 24, fieldValue3.y, true);
			}
			if (fieldValue3.z !== undefined) {
			view.setFloat32(byteOffset + 28, fieldValue3.z, true);
			}
		}
		if (value["min_distance"] !== undefined) {
		view.setFloat32(byteOffset + 32, value["min_distance"], true);
		}
		if (value["max_distance"] !== undefined) {
		view.setFloat32(byteOffset + 36, value["max_distance"], true);
		}
	},
};

export const ConstraintFixed = {
	name: "ConstraintFixed",
	id: 6,
	typeId: 6,
	size: 8,
	byteSize: 8,
	alignment: 4,
	fields: {
		"entity_a": { offset: 0, type: "u32" },
		"entity_b": { offset: 4, type: "u32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["entity_a"] = view.getUint32(byteOffset + 0, true);
		out["entity_b"] = view.getUint32(byteOffset + 4, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["entity_a"] !== undefined) {
		view.setUint32(byteOffset + 0, value["entity_a"], true);
		}
		if (value["entity_b"] !== undefined) {
		view.setUint32(byteOffset + 4, value["entity_b"], true);
		}
	},
};

export const ConstraintHinge = {
	name: "ConstraintHinge",
	id: 7,
	typeId: 7,
	size: 52,
	byteSize: 52,
	alignment: 4,
	fields: {
		"entity_a": { offset: 0, type: "u32" },
		"entity_b": { offset: 4, type: "u32" },
		"anchor": { offset: 8, type: "f32x3" },
		"hinge_axis": { offset: 20, type: "f32x3" },
		"normal_axis": { offset: 32, type: "f32x3" },
		"limit_min": { offset: 44, type: "f32" },
		"limit_max": { offset: 48, type: "f32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["entity_a"] = view.getUint32(byteOffset + 0, true);
		out["entity_b"] = view.getUint32(byteOffset + 4, true);
		out["anchor"] = { x: view.getFloat32(byteOffset + 8, true), y: view.getFloat32(byteOffset + 12, true), z: view.getFloat32(byteOffset + 16, true) };
		out["hinge_axis"] = { x: view.getFloat32(byteOffset + 20, true), y: view.getFloat32(byteOffset + 24, true), z: view.getFloat32(byteOffset + 28, true) };
		out["normal_axis"] = { x: view.getFloat32(byteOffset + 32, true), y: view.getFloat32(byteOffset + 36, true), z: view.getFloat32(byteOffset + 40, true) };
		out["limit_min"] = view.getFloat32(byteOffset + 44, true);
		out["limit_max"] = view.getFloat32(byteOffset + 48, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["entity_a"] !== undefined) {
		view.setUint32(byteOffset + 0, value["entity_a"], true);
		}
		if (value["entity_b"] !== undefined) {
		view.setUint32(byteOffset + 4, value["entity_b"], true);
		}
		const fieldValue2 = value["anchor"];
		if (fieldValue2 != null) {
			if (fieldValue2.x !== undefined) {
			view.setFloat32(byteOffset + 8, fieldValue2.x, true);
			}
			if (fieldValue2.y !== undefined) {
			view.setFloat32(byteOffset + 12, fieldValue2.y, true);
			}
			if (fieldValue2.z !== undefined) {
			view.setFloat32(byteOffset + 16, fieldValue2.z, true);
			}
		}
		const fieldValue3 = value["hinge_axis"];
		if (fieldValue3 != null) {
			if (fieldValue3.x !== undefined) {
			view.setFloat32(byteOffset + 20, fieldValue3.x, true);
			}
			if (fieldValue3.y !== undefined) {
			view.setFloat32(byteOffset + 24, fieldValue3.y, true);
			}
			if (fieldValue3.z !== undefined) {
			view.setFloat32(byteOffset + 28, fieldValue3.z, true);
			}
		}
		const fieldValue4 = value["normal_axis"];
		if (fieldValue4 != null) {
			if (fieldValue4.x !== undefined) {
			view.setFloat32(byteOffset + 32, fieldValue4.x, true);
			}
			if (fieldValue4.y !== undefined) {
			view.setFloat32(byteOffset + 36, fieldValue4.y, true);
			}
			if (fieldValue4.z !== undefined) {
			view.setFloat32(byteOffset + 40, fieldValue4.z, true);
			}
		}
		if (value["limit_min"] !== undefined) {
		view.setFloat32(byteOffset + 44, value["limit_min"], true);
		}
		if (value["limit_max"] !== undefined) {
		view.setFloat32(byteOffset + 48, value["limit_max"], true);
		}
	},
};

export const ConstraintPoint = {
	name: "ConstraintPoint",
	id: 8,
	typeId: 8,
	size: 20,
	byteSize: 20,
	alignment: 4,
	fields: {
		"entity_a": { offset: 0, type: "u32" },
		"entity_b": { offset: 4, type: "u32" },
		"anchor": { offset: 8, type: "f32x3" },
	},
	read(view, byteOffset) {
		const out = {};
		out["entity_a"] = view.getUint32(byteOffset + 0, true);
		out["entity_b"] = view.getUint32(byteOffset + 4, true);
		out["anchor"] = { x: view.getFloat32(byteOffset + 8, true), y: view.getFloat32(byteOffset + 12, true), z: view.getFloat32(byteOffset + 16, true) };
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["entity_a"] !== undefined) {
		view.setUint32(byteOffset + 0, value["entity_a"], true);
		}
		if (value["entity_b"] !== undefined) {
		view.setUint32(byteOffset + 4, value["entity_b"], true);
		}
		const fieldValue2 = value["anchor"];
		if (fieldValue2 != null) {
			if (fieldValue2.x !== undefined) {
			view.setFloat32(byteOffset + 8, fieldValue2.x, true);
			}
			if (fieldValue2.y !== undefined) {
			view.setFloat32(byteOffset + 12, fieldValue2.y, true);
			}
			if (fieldValue2.z !== undefined) {
			view.setFloat32(byteOffset + 16, fieldValue2.z, true);
			}
		}
	},
};

export const ConstraintSlider = {
	name: "ConstraintSlider",
	id: 9,
	typeId: 9,
	size: 28,
	byteSize: 28,
	alignment: 4,
	fields: {
		"entity_a": { offset: 0, type: "u32" },
		"entity_b": { offset: 4, type: "u32" },
		"slider_axis": { offset: 8, type: "f32x3" },
		"limit_min": { offset: 20, type: "f32" },
		"limit_max": { offset: 24, type: "f32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["entity_a"] = view.getUint32(byteOffset + 0, true);
		out["entity_b"] = view.getUint32(byteOffset + 4, true);
		out["slider_axis"] = { x: view.getFloat32(byteOffset + 8, true), y: view.getFloat32(byteOffset + 12, true), z: view.getFloat32(byteOffset + 16, true) };
		out["limit_min"] = view.getFloat32(byteOffset + 20, true);
		out["limit_max"] = view.getFloat32(byteOffset + 24, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["entity_a"] !== undefined) {
		view.setUint32(byteOffset + 0, value["entity_a"], true);
		}
		if (value["entity_b"] !== undefined) {
		view.setUint32(byteOffset + 4, value["entity_b"], true);
		}
		const fieldValue2 = value["slider_axis"];
		if (fieldValue2 != null) {
			if (fieldValue2.x !== undefined) {
			view.setFloat32(byteOffset + 8, fieldValue2.x, true);
			}
			if (fieldValue2.y !== undefined) {
			view.setFloat32(byteOffset + 12, fieldValue2.y, true);
			}
			if (fieldValue2.z !== undefined) {
			view.setFloat32(byteOffset + 16, fieldValue2.z, true);
			}
		}
		if (value["limit_min"] !== undefined) {
		view.setFloat32(byteOffset + 20, value["limit_min"], true);
		}
		if (value["limit_max"] !== undefined) {
		view.setFloat32(byteOffset + 24, value["limit_max"], true);
		}
	},
};

export const ConstraintSwingTwist = {
	name: "ConstraintSwingTwist",
	id: 10,
	typeId: 10,
	size: 60,
	byteSize: 60,
	alignment: 4,
	fields: {
		"entity_a": { offset: 0, type: "u32" },
		"entity_b": { offset: 4, type: "u32" },
		"anchor": { offset: 8, type: "f32x3" },
		"twist_axis": { offset: 20, type: "f32x3" },
		"plane_axis": { offset: 32, type: "f32x3" },
		"normal_half_cone_angle": { offset: 44, type: "f32" },
		"plane_half_cone_angle": { offset: 48, type: "f32" },
		"twist_min_angle": { offset: 52, type: "f32" },
		"twist_max_angle": { offset: 56, type: "f32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["entity_a"] = view.getUint32(byteOffset + 0, true);
		out["entity_b"] = view.getUint32(byteOffset + 4, true);
		out["anchor"] = { x: view.getFloat32(byteOffset + 8, true), y: view.getFloat32(byteOffset + 12, true), z: view.getFloat32(byteOffset + 16, true) };
		out["twist_axis"] = { x: view.getFloat32(byteOffset + 20, true), y: view.getFloat32(byteOffset + 24, true), z: view.getFloat32(byteOffset + 28, true) };
		out["plane_axis"] = { x: view.getFloat32(byteOffset + 32, true), y: view.getFloat32(byteOffset + 36, true), z: view.getFloat32(byteOffset + 40, true) };
		out["normal_half_cone_angle"] = view.getFloat32(byteOffset + 44, true);
		out["plane_half_cone_angle"] = view.getFloat32(byteOffset + 48, true);
		out["twist_min_angle"] = view.getFloat32(byteOffset + 52, true);
		out["twist_max_angle"] = view.getFloat32(byteOffset + 56, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["entity_a"] !== undefined) {
		view.setUint32(byteOffset + 0, value["entity_a"], true);
		}
		if (value["entity_b"] !== undefined) {
		view.setUint32(byteOffset + 4, value["entity_b"], true);
		}
		const fieldValue2 = value["anchor"];
		if (fieldValue2 != null) {
			if (fieldValue2.x !== undefined) {
			view.setFloat32(byteOffset + 8, fieldValue2.x, true);
			}
			if (fieldValue2.y !== undefined) {
			view.setFloat32(byteOffset + 12, fieldValue2.y, true);
			}
			if (fieldValue2.z !== undefined) {
			view.setFloat32(byteOffset + 16, fieldValue2.z, true);
			}
		}
		const fieldValue3 = value["twist_axis"];
		if (fieldValue3 != null) {
			if (fieldValue3.x !== undefined) {
			view.setFloat32(byteOffset + 20, fieldValue3.x, true);
			}
			if (fieldValue3.y !== undefined) {
			view.setFloat32(byteOffset + 24, fieldValue3.y, true);
			}
			if (fieldValue3.z !== undefined) {
			view.setFloat32(byteOffset + 28, fieldValue3.z, true);
			}
		}
		const fieldValue4 = value["plane_axis"];
		if (fieldValue4 != null) {
			if (fieldValue4.x !== undefined) {
			view.setFloat32(byteOffset + 32, fieldValue4.x, true);
			}
			if (fieldValue4.y !== undefined) {
			view.setFloat32(byteOffset + 36, fieldValue4.y, true);
			}
			if (fieldValue4.z !== undefined) {
			view.setFloat32(byteOffset + 40, fieldValue4.z, true);
			}
		}
		if (value["normal_half_cone_angle"] !== undefined) {
		view.setFloat32(byteOffset + 44, value["normal_half_cone_angle"], true);
		}
		if (value["plane_half_cone_angle"] !== undefined) {
		view.setFloat32(byteOffset + 48, value["plane_half_cone_angle"], true);
		}
		if (value["twist_min_angle"] !== undefined) {
		view.setFloat32(byteOffset + 52, value["twist_min_angle"], true);
		}
		if (value["twist_max_angle"] !== undefined) {
		view.setFloat32(byteOffset + 56, value["twist_max_angle"], true);
		}
	},
};

export const DirectionalLight = {
	name: "DirectionalLight",
	id: 11,
	typeId: 11,
	size: 16,
	byteSize: 16,
	alignment: 4,
	fields: {
		"direction": { offset: 0, type: "f32x3" },
		"illuminance": { offset: 12, type: "f32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["direction"] = { x: view.getFloat32(byteOffset + 0, true), y: view.getFloat32(byteOffset + 4, true), z: view.getFloat32(byteOffset + 8, true) };
		out["illuminance"] = view.getFloat32(byteOffset + 12, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		const fieldValue0 = value["direction"];
		if (fieldValue0 != null) {
			if (fieldValue0.x !== undefined) {
			view.setFloat32(byteOffset + 0, fieldValue0.x, true);
			}
			if (fieldValue0.y !== undefined) {
			view.setFloat32(byteOffset + 4, fieldValue0.y, true);
			}
			if (fieldValue0.z !== undefined) {
			view.setFloat32(byteOffset + 8, fieldValue0.z, true);
			}
		}
		if (value["illuminance"] !== undefined) {
		view.setFloat32(byteOffset + 12, value["illuminance"], true);
		}
	},
};

export const DirectionalLightSettings = {
	name: "DirectionalLightSettings",
	id: 12,
	typeId: 12,
	size: 16,
	byteSize: 16,
	alignment: 4,
	fields: {
		"sun_color": { offset: 0, type: "f32x3" },
		"ambient_intensity": { offset: 12, type: "f32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["sun_color"] = { x: view.getFloat32(byteOffset + 0, true), y: view.getFloat32(byteOffset + 4, true), z: view.getFloat32(byteOffset + 8, true) };
		out["ambient_intensity"] = view.getFloat32(byteOffset + 12, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		const fieldValue0 = value["sun_color"];
		if (fieldValue0 != null) {
			if (fieldValue0.x !== undefined) {
			view.setFloat32(byteOffset + 0, fieldValue0.x, true);
			}
			if (fieldValue0.y !== undefined) {
			view.setFloat32(byteOffset + 4, fieldValue0.y, true);
			}
			if (fieldValue0.z !== undefined) {
			view.setFloat32(byteOffset + 8, fieldValue0.z, true);
			}
		}
		if (value["ambient_intensity"] !== undefined) {
		view.setFloat32(byteOffset + 12, value["ambient_intensity"], true);
		}
	},
};

export const DoNotSerialize = {
	name: "DoNotSerialize",
	id: 13,
	typeId: 13,
	size: 0,
	byteSize: 0,
	fields: {
	},
	read(view, byteOffset) {
		return {};
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
	},
};

export const EntityMetadata = {
	name: "EntityMetadata",
	id: 14,
	typeId: 14,
	size: 8,
	byteSize: 8,
	alignment: 4,
	fields: {
		"title": { offset: 0, type: "text_id" },
		"description": { offset: 4, type: "text_id" },
	},
	read(view, byteOffset) {
		const out = {};
		out["title"] = view.getUint32(byteOffset + 0, true);
		out["description"] = view.getUint32(byteOffset + 4, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["title"] !== undefined) {
		view.setUint32(byteOffset + 0, value["title"], true);
		}
		if (value["description"] !== undefined) {
		view.setUint32(byteOffset + 4, value["description"], true);
		}
	},
};

export const EnvironmentSettings = {
	name: "EnvironmentSettings",
	id: 15,
	typeId: 15,
	size: 4,
	byteSize: 4,
	alignment: 4,
	fields: {
		"sky_cubemap_name_hash": { offset: 0, type: "u32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["sky_cubemap_name_hash"] = view.getUint32(byteOffset + 0, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["sky_cubemap_name_hash"] !== undefined) {
		view.setUint32(byteOffset + 0, value["sky_cubemap_name_hash"], true);
		}
	},
};

export const Gizmo = {
	name: "Gizmo",
	id: 16,
	typeId: 16,
	size: 2,
	byteSize: 2,
	alignment: 1,
	fields: {
		"gizmo_type": { offset: 0, type: "u8" },
		"selected_axes": { offset: 1, type: "u8" },
	},
	read(view, byteOffset) {
		const out = {};
		out["gizmo_type"] = view.getUint8(byteOffset + 0);
		out["selected_axes"] = view.getUint8(byteOffset + 1);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["gizmo_type"] !== undefined) {
		view.setUint8(byteOffset + 0, value["gizmo_type"]);
		}
		if (value["selected_axes"] !== undefined) {
		view.setUint8(byteOffset + 1, value["selected_axes"]);
		}
	},
};

export const Hierarchy = {
	name: "Hierarchy",
	id: 17,
	typeId: 17,
	size: 16,
	byteSize: 16,
	alignment: 4,
	fields: {
		"first_child": { offset: 0, type: "u32" },
		"parent": { offset: 4, type: "u32" },
		"prev_sibling": { offset: 8, type: "u32" },
		"next_sibling": { offset: 12, type: "u32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["first_child"] = view.getUint32(byteOffset + 0, true);
		out["parent"] = view.getUint32(byteOffset + 4, true);
		out["prev_sibling"] = view.getUint32(byteOffset + 8, true);
		out["next_sibling"] = view.getUint32(byteOffset + 12, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["first_child"] !== undefined) {
		view.setUint32(byteOffset + 0, value["first_child"], true);
		}
		if (value["parent"] !== undefined) {
		view.setUint32(byteOffset + 4, value["parent"], true);
		}
		if (value["prev_sibling"] !== undefined) {
		view.setUint32(byteOffset + 8, value["prev_sibling"], true);
		}
		if (value["next_sibling"] !== undefined) {
		view.setUint32(byteOffset + 12, value["next_sibling"], true);
		}
	},
};

export const MainCamera = {
	name: "MainCamera",
	id: 18,
	typeId: 18,
	size: 0,
	byteSize: 0,
	fields: {
	},
	read(view, byteOffset) {
		return {};
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
	},
};

export const MeshCollision = {
	name: "MeshCollision",
	id: 19,
	typeId: 19,
	size: 4,
	byteSize: 4,
	alignment: 4,
	fields: {
		"mesh": { offset: 0, type: "u32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["mesh"] = view.getUint32(byteOffset + 0, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["mesh"] !== undefined) {
		view.setUint32(byteOffset + 0, value["mesh"], true);
		}
	},
};

export const MeshRenderer = {
	name: "MeshRenderer",
	id: 20,
	typeId: 20,
	size: 12,
	byteSize: 12,
	alignment: 4,
	fields: {
		"mesh": { offset: 0, type: "u32" },
		"material": { offset: 4, type: "u32" },
		"color": { offset: 8, type: "u8x4" },
	},
	read(view, byteOffset) {
		const out = {};
		out["mesh"] = view.getUint32(byteOffset + 0, true);
		out["material"] = view.getUint32(byteOffset + 4, true);
		out["color"] = { x: view.getUint8(byteOffset + 8), y: view.getUint8(byteOffset + 9), z: view.getUint8(byteOffset + 10), w: view.getUint8(byteOffset + 11) };
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["mesh"] !== undefined) {
		view.setUint32(byteOffset + 0, value["mesh"], true);
		}
		if (value["material"] !== undefined) {
		view.setUint32(byteOffset + 4, value["material"], true);
		}
		const fieldValue2 = value["color"];
		if (fieldValue2 != null) {
			if (fieldValue2.x !== undefined) {
			view.setUint8(byteOffset + 8, fieldValue2.x);
			}
			if (fieldValue2.y !== undefined) {
			view.setUint8(byteOffset + 9, fieldValue2.y);
			}
			if (fieldValue2.z !== undefined) {
			view.setUint8(byteOffset + 10, fieldValue2.z);
			}
			if (fieldValue2.w !== undefined) {
			view.setUint8(byteOffset + 11, fieldValue2.w);
			}
		}
	},
};

export const PostProcessSettings = {
	name: "PostProcessSettings",
	id: 21,
	typeId: 21,
	size: 76,
	byteSize: 76,
	alignment: 4,
	fields: {
		"bloom_intensity": { offset: 0, type: "f32" },
		"bloom_size": { offset: 4, type: "f32" },
		"bloom_threshold": { offset: 8, type: "f32" },
		"exposure": { offset: 12, type: "f32" },
		"vignette_strength": { offset: 16, type: "f32" },
		"vignette_threshold": { offset: 20, type: "f32" },
		"vignette_color": { offset: 24, type: "f32x4" },
		"brightness": { offset: 40, type: "f32" },
		"contrast": { offset: 44, type: "f32" },
		"saturation": { offset: 48, type: "f32" },
		"highlights": { offset: 52, type: "f32" },
		"shadows": { offset: 56, type: "f32" },
		"tint": { offset: 60, type: "f32x3" },
		"tint_strength": { offset: 72, type: "f32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["bloom_intensity"] = view.getFloat32(byteOffset + 0, true);
		out["bloom_size"] = view.getFloat32(byteOffset + 4, true);
		out["bloom_threshold"] = view.getFloat32(byteOffset + 8, true);
		out["exposure"] = view.getFloat32(byteOffset + 12, true);
		out["vignette_strength"] = view.getFloat32(byteOffset + 16, true);
		out["vignette_threshold"] = view.getFloat32(byteOffset + 20, true);
		out["vignette_color"] = { x: view.getFloat32(byteOffset + 24, true), y: view.getFloat32(byteOffset + 28, true), z: view.getFloat32(byteOffset + 32, true), w: view.getFloat32(byteOffset + 36, true) };
		out["brightness"] = view.getFloat32(byteOffset + 40, true);
		out["contrast"] = view.getFloat32(byteOffset + 44, true);
		out["saturation"] = view.getFloat32(byteOffset + 48, true);
		out["highlights"] = view.getFloat32(byteOffset + 52, true);
		out["shadows"] = view.getFloat32(byteOffset + 56, true);
		out["tint"] = { x: view.getFloat32(byteOffset + 60, true), y: view.getFloat32(byteOffset + 64, true), z: view.getFloat32(byteOffset + 68, true) };
		out["tint_strength"] = view.getFloat32(byteOffset + 72, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["bloom_intensity"] !== undefined) {
		view.setFloat32(byteOffset + 0, value["bloom_intensity"], true);
		}
		if (value["bloom_size"] !== undefined) {
		view.setFloat32(byteOffset + 4, value["bloom_size"], true);
		}
		if (value["bloom_threshold"] !== undefined) {
		view.setFloat32(byteOffset + 8, value["bloom_threshold"], true);
		}
		if (value["exposure"] !== undefined) {
		view.setFloat32(byteOffset + 12, value["exposure"], true);
		}
		if (value["vignette_strength"] !== undefined) {
		view.setFloat32(byteOffset + 16, value["vignette_strength"], true);
		}
		if (value["vignette_threshold"] !== undefined) {
		view.setFloat32(byteOffset + 20, value["vignette_threshold"], true);
		}
		const fieldValue6 = value["vignette_color"];
		if (fieldValue6 != null) {
			if (fieldValue6.x !== undefined) {
			view.setFloat32(byteOffset + 24, fieldValue6.x, true);
			}
			if (fieldValue6.y !== undefined) {
			view.setFloat32(byteOffset + 28, fieldValue6.y, true);
			}
			if (fieldValue6.z !== undefined) {
			view.setFloat32(byteOffset + 32, fieldValue6.z, true);
			}
			if (fieldValue6.w !== undefined) {
			view.setFloat32(byteOffset + 36, fieldValue6.w, true);
			}
		}
		if (value["brightness"] !== undefined) {
		view.setFloat32(byteOffset + 40, value["brightness"], true);
		}
		if (value["contrast"] !== undefined) {
		view.setFloat32(byteOffset + 44, value["contrast"], true);
		}
		if (value["saturation"] !== undefined) {
		view.setFloat32(byteOffset + 48, value["saturation"], true);
		}
		if (value["highlights"] !== undefined) {
		view.setFloat32(byteOffset + 52, value["highlights"], true);
		}
		if (value["shadows"] !== undefined) {
		view.setFloat32(byteOffset + 56, value["shadows"], true);
		}
		const fieldValue12 = value["tint"];
		if (fieldValue12 != null) {
			if (fieldValue12.x !== undefined) {
			view.setFloat32(byteOffset + 60, fieldValue12.x, true);
			}
			if (fieldValue12.y !== undefined) {
			view.setFloat32(byteOffset + 64, fieldValue12.y, true);
			}
			if (fieldValue12.z !== undefined) {
			view.setFloat32(byteOffset + 68, fieldValue12.z, true);
			}
		}
		if (value["tint_strength"] !== undefined) {
		view.setFloat32(byteOffset + 72, value["tint_strength"], true);
		}
	},
};

export const RigidBody = {
	name: "RigidBody",
	id: 22,
	typeId: 22,
	size: 20,
	byteSize: 20,
	alignment: 4,
	fields: {
		"motion_type": { offset: 0, type: "u8" },
		"restitution": { offset: 4, type: "f32" },
		"friction": { offset: 8, type: "f32" },
		"linear_damping": { offset: 12, type: "f32" },
		"angular_damping": { offset: 16, type: "f32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["motion_type"] = view.getUint8(byteOffset + 0);
		out["restitution"] = view.getFloat32(byteOffset + 4, true);
		out["friction"] = view.getFloat32(byteOffset + 8, true);
		out["linear_damping"] = view.getFloat32(byteOffset + 12, true);
		out["angular_damping"] = view.getFloat32(byteOffset + 16, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["motion_type"] !== undefined) {
		view.setUint8(byteOffset + 0, value["motion_type"]);
		}
		if (value["restitution"] !== undefined) {
		view.setFloat32(byteOffset + 4, value["restitution"], true);
		}
		if (value["friction"] !== undefined) {
		view.setFloat32(byteOffset + 8, value["friction"], true);
		}
		if (value["linear_damping"] !== undefined) {
		view.setFloat32(byteOffset + 12, value["linear_damping"], true);
		}
		if (value["angular_damping"] !== undefined) {
		view.setFloat32(byteOffset + 16, value["angular_damping"], true);
		}
	},
};

export const Root = {
	name: "Root",
	id: 23,
	typeId: 23,
	size: 0,
	byteSize: 0,
	fields: {
	},
	read(view, byteOffset) {
		return {};
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
	},
};

export const Selected = {
	name: "Selected",
	id: 24,
	typeId: 24,
	size: 5,
	byteSize: 5,
	alignment: 1,
	fields: {
		"outline_type": { offset: 0, type: "u8" },
		"color": { offset: 1, type: "u8x4" },
	},
	read(view, byteOffset) {
		const out = {};
		out["outline_type"] = view.getUint8(byteOffset + 0);
		out["color"] = { x: view.getUint8(byteOffset + 1), y: view.getUint8(byteOffset + 2), z: view.getUint8(byteOffset + 3), w: view.getUint8(byteOffset + 4) };
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["outline_type"] !== undefined) {
		view.setUint8(byteOffset + 0, value["outline_type"]);
		}
		const fieldValue1 = value["color"];
		if (fieldValue1 != null) {
			if (fieldValue1.x !== undefined) {
			view.setUint8(byteOffset + 1, fieldValue1.x);
			}
			if (fieldValue1.y !== undefined) {
			view.setUint8(byteOffset + 2, fieldValue1.y);
			}
			if (fieldValue1.z !== undefined) {
			view.setUint8(byteOffset + 3, fieldValue1.z);
			}
			if (fieldValue1.w !== undefined) {
			view.setUint8(byteOffset + 4, fieldValue1.w);
			}
		}
	},
};

export const SkeletonAnimation = {
	name: "SkeletonAnimation",
	id: 25,
	typeId: 25,
	size: 20,
	byteSize: 20,
	alignment: 4,
	fields: {
		"state_machine": { offset: 0, type: "u32" },
		"skeleton": { offset: 4, type: "u32" },
		"anim_clip": { offset: 8, type: "u32" },
		"action_clip": { offset: 12, type: "u32" },
		"remove_trajectory": { offset: 16, type: "bool" },
	},
	read(view, byteOffset) {
		const out = {};
		out["state_machine"] = view.getUint32(byteOffset + 0, true);
		out["skeleton"] = view.getUint32(byteOffset + 4, true);
		out["anim_clip"] = view.getUint32(byteOffset + 8, true);
		out["action_clip"] = view.getUint32(byteOffset + 12, true);
		out["remove_trajectory"] = (view.getUint8(byteOffset + 16) !== 0);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["state_machine"] !== undefined) {
		view.setUint32(byteOffset + 0, value["state_machine"], true);
		}
		if (value["skeleton"] !== undefined) {
		view.setUint32(byteOffset + 4, value["skeleton"], true);
		}
		if (value["anim_clip"] !== undefined) {
		view.setUint32(byteOffset + 8, value["anim_clip"], true);
		}
		if (value["action_clip"] !== undefined) {
		view.setUint32(byteOffset + 12, value["action_clip"], true);
		}
		if (value["remove_trajectory"] !== undefined) {
		view.setUint8(byteOffset + 16, (value["remove_trajectory"]) ? 1 : 0);
		}
	},
};

export const SphereCollision = {
	name: "SphereCollision",
	id: 26,
	typeId: 26,
	size: 4,
	byteSize: 4,
	alignment: 4,
	fields: {
		"radius": { offset: 0, type: "f32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["radius"] = view.getFloat32(byteOffset + 0, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["radius"] !== undefined) {
		view.setFloat32(byteOffset + 0, value["radius"], true);
		}
	},
};

export const Text = {
	name: "Text",
	id: 27,
	typeId: 27,
	size: 4,
	byteSize: 4,
	alignment: 4,
	fields: {
		"text_id": { offset: 0, type: "text_id" },
	},
	read(view, byteOffset) {
		const out = {};
		out["text_id"] = view.getUint32(byteOffset + 0, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["text_id"] !== undefined) {
		view.setUint32(byteOffset + 0, value["text_id"], true);
		}
	},
};

export const Transform = {
	name: "Transform",
	id: 28,
	typeId: 28,
	size: 44,
	byteSize: 44,
	alignment: 4,
	fields: {
		"position": { offset: 0, type: "f32x3" },
		"rotation": { offset: 12, type: "f32x4" },
		"scale": { offset: 28, type: "f32x3" },
		"detached_from_parent": { offset: 40, type: "bool" },
	},
	read(view, byteOffset) {
		const out = {};
		out["position"] = { x: view.getFloat32(byteOffset + 0, true), y: view.getFloat32(byteOffset + 4, true), z: view.getFloat32(byteOffset + 8, true) };
		out["rotation"] = { x: view.getFloat32(byteOffset + 12, true), y: view.getFloat32(byteOffset + 16, true), z: view.getFloat32(byteOffset + 20, true), w: view.getFloat32(byteOffset + 24, true) };
		out["scale"] = { x: view.getFloat32(byteOffset + 28, true), y: view.getFloat32(byteOffset + 32, true), z: view.getFloat32(byteOffset + 36, true) };
		out["detached_from_parent"] = (view.getUint8(byteOffset + 40) !== 0);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		const fieldValue0 = value["position"];
		if (fieldValue0 != null) {
			if (fieldValue0.x !== undefined) {
			view.setFloat32(byteOffset + 0, fieldValue0.x, true);
			}
			if (fieldValue0.y !== undefined) {
			view.setFloat32(byteOffset + 4, fieldValue0.y, true);
			}
			if (fieldValue0.z !== undefined) {
			view.setFloat32(byteOffset + 8, fieldValue0.z, true);
			}
		}
		const fieldValue1 = value["rotation"];
		if (fieldValue1 != null) {
			if (fieldValue1.x !== undefined) {
			view.setFloat32(byteOffset + 12, fieldValue1.x, true);
			}
			if (fieldValue1.y !== undefined) {
			view.setFloat32(byteOffset + 16, fieldValue1.y, true);
			}
			if (fieldValue1.z !== undefined) {
			view.setFloat32(byteOffset + 20, fieldValue1.z, true);
			}
			if (fieldValue1.w !== undefined) {
			view.setFloat32(byteOffset + 24, fieldValue1.w, true);
			}
		}
		const fieldValue2 = value["scale"];
		if (fieldValue2 != null) {
			if (fieldValue2.x !== undefined) {
			view.setFloat32(byteOffset + 28, fieldValue2.x, true);
			}
			if (fieldValue2.y !== undefined) {
			view.setFloat32(byteOffset + 32, fieldValue2.y, true);
			}
			if (fieldValue2.z !== undefined) {
			view.setFloat32(byteOffset + 36, fieldValue2.z, true);
			}
		}
		if (value["detached_from_parent"] !== undefined) {
		view.setUint8(byteOffset + 40, (value["detached_from_parent"]) ? 1 : 0);
		}
	},
};

export const WaterSettings = {
	name: "WaterSettings",
	id: 29,
	typeId: 29,
	size: 88,
	byteSize: 88,
	alignment: 4,
	fields: {
		"enabled": { offset: 0, type: "bool" },
		"y": { offset: 4, type: "f32" },
		"amplitude": { offset: 8, type: "f32" },
		"direction": { offset: 12, type: "f32" },
		"speed": { offset: 16, type: "f32" },
		"albedo": { offset: 20, type: "f32x3" },
		"extinction": { offset: 32, type: "f32" },
		"wave_profile": { offset: 36, type: "u32" },
		"wave_size": { offset: 40, type: "f32" },
		"foam_profile": { offset: 44, type: "u32" },
		"foam_size": { offset: 48, type: "f32" },
		"foam_range": { offset: 52, type: "f32" },
		"foam_albedo": { offset: 56, type: "f32x3" },
		"foam_opacity": { offset: 68, type: "f32" },
		"foam_speed": { offset: 72, type: "f32" },
		"caustics_profile": { offset: 76, type: "u32" },
		"caustics_size": { offset: 80, type: "f32" },
		"caustics_brightness": { offset: 84, type: "f32" },
	},
	read(view, byteOffset) {
		const out = {};
		out["enabled"] = (view.getUint8(byteOffset + 0) !== 0);
		out["y"] = view.getFloat32(byteOffset + 4, true);
		out["amplitude"] = view.getFloat32(byteOffset + 8, true);
		out["direction"] = view.getFloat32(byteOffset + 12, true);
		out["speed"] = view.getFloat32(byteOffset + 16, true);
		out["albedo"] = { x: view.getFloat32(byteOffset + 20, true), y: view.getFloat32(byteOffset + 24, true), z: view.getFloat32(byteOffset + 28, true) };
		out["extinction"] = view.getFloat32(byteOffset + 32, true);
		out["wave_profile"] = view.getUint32(byteOffset + 36, true);
		out["wave_size"] = view.getFloat32(byteOffset + 40, true);
		out["foam_profile"] = view.getUint32(byteOffset + 44, true);
		out["foam_size"] = view.getFloat32(byteOffset + 48, true);
		out["foam_range"] = view.getFloat32(byteOffset + 52, true);
		out["foam_albedo"] = { x: view.getFloat32(byteOffset + 56, true), y: view.getFloat32(byteOffset + 60, true), z: view.getFloat32(byteOffset + 64, true) };
		out["foam_opacity"] = view.getFloat32(byteOffset + 68, true);
		out["foam_speed"] = view.getFloat32(byteOffset + 72, true);
		out["caustics_profile"] = view.getUint32(byteOffset + 76, true);
		out["caustics_size"] = view.getFloat32(byteOffset + 80, true);
		out["caustics_brightness"] = view.getFloat32(byteOffset + 84, true);
		return out;
	},
	write(view, byteOffset, value) {
		if (value == null)
			return;
		if (value["enabled"] !== undefined) {
		view.setUint8(byteOffset + 0, (value["enabled"]) ? 1 : 0);
		}
		if (value["y"] !== undefined) {
		view.setFloat32(byteOffset + 4, value["y"], true);
		}
		if (value["amplitude"] !== undefined) {
		view.setFloat32(byteOffset + 8, value["amplitude"], true);
		}
		if (value["direction"] !== undefined) {
		view.setFloat32(byteOffset + 12, value["direction"], true);
		}
		if (value["speed"] !== undefined) {
		view.setFloat32(byteOffset + 16, value["speed"], true);
		}
		const fieldValue5 = value["albedo"];
		if (fieldValue5 != null) {
			if (fieldValue5.x !== undefined) {
			view.setFloat32(byteOffset + 20, fieldValue5.x, true);
			}
			if (fieldValue5.y !== undefined) {
			view.setFloat32(byteOffset + 24, fieldValue5.y, true);
			}
			if (fieldValue5.z !== undefined) {
			view.setFloat32(byteOffset + 28, fieldValue5.z, true);
			}
		}
		if (value["extinction"] !== undefined) {
		view.setFloat32(byteOffset + 32, value["extinction"], true);
		}
		if (value["wave_profile"] !== undefined) {
		view.setUint32(byteOffset + 36, value["wave_profile"], true);
		}
		if (value["wave_size"] !== undefined) {
		view.setFloat32(byteOffset + 40, value["wave_size"], true);
		}
		if (value["foam_profile"] !== undefined) {
		view.setUint32(byteOffset + 44, value["foam_profile"], true);
		}
		if (value["foam_size"] !== undefined) {
		view.setFloat32(byteOffset + 48, value["foam_size"], true);
		}
		if (value["foam_range"] !== undefined) {
		view.setFloat32(byteOffset + 52, value["foam_range"], true);
		}
		const fieldValue12 = value["foam_albedo"];
		if (fieldValue12 != null) {
			if (fieldValue12.x !== undefined) {
			view.setFloat32(byteOffset + 56, fieldValue12.x, true);
			}
			if (fieldValue12.y !== undefined) {
			view.setFloat32(byteOffset + 60, fieldValue12.y, true);
			}
			if (fieldValue12.z !== undefined) {
			view.setFloat32(byteOffset + 64, fieldValue12.z, true);
			}
		}
		if (value["foam_opacity"] !== undefined) {
		view.setFloat32(byteOffset + 68, value["foam_opacity"], true);
		}
		if (value["foam_speed"] !== undefined) {
		view.setFloat32(byteOffset + 72, value["foam_speed"], true);
		}
		if (value["caustics_profile"] !== undefined) {
		view.setUint32(byteOffset + 76, value["caustics_profile"], true);
		}
		if (value["caustics_size"] !== undefined) {
		view.setFloat32(byteOffset + 80, value["caustics_size"], true);
		}
		if (value["caustics_brightness"] !== undefined) {
		view.setFloat32(byteOffset + 84, value["caustics_brightness"], true);
		}
	},
};

export const AliveOps = {
};

export const AssetReferenceOps = {
	getAssetIndex(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setAssetIndex(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
	getAssetNameHash(Module, ptr) {
		return Module.HEAPU32[(ptr + 4) >>> 2];
	},
	setAssetNameHash(Module, ptr, value) {
		Module.HEAPU32[(ptr + 4) >>> 2] = value;
	},
};

export const BoxCollisionOps = {
	getHalfExtentsX(Module, ptr) {
		return Module.HEAPF32[(ptr + 0) >>> 2];
	},
	setHalfExtentsX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 0) >>> 2] = value;
	},
	getHalfExtentsY(Module, ptr) {
		return Module.HEAPF32[(ptr + 4) >>> 2];
	},
	setHalfExtentsY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 4) >>> 2] = value;
	},
	getHalfExtentsZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 8) >>> 2];
	},
	setHalfExtentsZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 8) >>> 2] = value;
	},
};

export const CameraOps = {
	getFov(Module, ptr) {
		return Module.HEAPF32[(ptr + 0) >>> 2];
	},
	setFov(Module, ptr, value) {
		Module.HEAPF32[(ptr + 0) >>> 2] = value;
	},
	getNear(Module, ptr) {
		return Module.HEAPF32[(ptr + 4) >>> 2];
	},
	setNear(Module, ptr, value) {
		Module.HEAPF32[(ptr + 4) >>> 2] = value;
	},
	getFar(Module, ptr) {
		return Module.HEAPF32[(ptr + 8) >>> 2];
	},
	setFar(Module, ptr, value) {
		Module.HEAPF32[(ptr + 8) >>> 2] = value;
	},
};

export const CapsuleCollisionOps = {
	getRadius(Module, ptr) {
		return Module.HEAPF32[(ptr + 0) >>> 2];
	},
	setRadius(Module, ptr, value) {
		Module.HEAPF32[(ptr + 0) >>> 2] = value;
	},
	getHalfHeight(Module, ptr) {
		return Module.HEAPF32[(ptr + 4) >>> 2];
	},
	setHalfHeight(Module, ptr, value) {
		Module.HEAPF32[(ptr + 4) >>> 2] = value;
	},
};

export const ConstraintDistanceOps = {
	getEntityA(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setEntityA(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
	getEntityB(Module, ptr) {
		return Module.HEAPU32[(ptr + 4) >>> 2];
	},
	setEntityB(Module, ptr, value) {
		Module.HEAPU32[(ptr + 4) >>> 2] = value;
	},
	getAnchorAX(Module, ptr) {
		return Module.HEAPF32[(ptr + 8) >>> 2];
	},
	setAnchorAX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 8) >>> 2] = value;
	},
	getAnchorAY(Module, ptr) {
		return Module.HEAPF32[(ptr + 12) >>> 2];
	},
	setAnchorAY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 12) >>> 2] = value;
	},
	getAnchorAZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 16) >>> 2];
	},
	setAnchorAZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 16) >>> 2] = value;
	},
	getAnchorBX(Module, ptr) {
		return Module.HEAPF32[(ptr + 20) >>> 2];
	},
	setAnchorBX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 20) >>> 2] = value;
	},
	getAnchorBY(Module, ptr) {
		return Module.HEAPF32[(ptr + 24) >>> 2];
	},
	setAnchorBY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 24) >>> 2] = value;
	},
	getAnchorBZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 28) >>> 2];
	},
	setAnchorBZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 28) >>> 2] = value;
	},
	getMinDistance(Module, ptr) {
		return Module.HEAPF32[(ptr + 32) >>> 2];
	},
	setMinDistance(Module, ptr, value) {
		Module.HEAPF32[(ptr + 32) >>> 2] = value;
	},
	getMaxDistance(Module, ptr) {
		return Module.HEAPF32[(ptr + 36) >>> 2];
	},
	setMaxDistance(Module, ptr, value) {
		Module.HEAPF32[(ptr + 36) >>> 2] = value;
	},
};

export const ConstraintFixedOps = {
	getEntityA(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setEntityA(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
	getEntityB(Module, ptr) {
		return Module.HEAPU32[(ptr + 4) >>> 2];
	},
	setEntityB(Module, ptr, value) {
		Module.HEAPU32[(ptr + 4) >>> 2] = value;
	},
};

export const ConstraintHingeOps = {
	getEntityA(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setEntityA(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
	getEntityB(Module, ptr) {
		return Module.HEAPU32[(ptr + 4) >>> 2];
	},
	setEntityB(Module, ptr, value) {
		Module.HEAPU32[(ptr + 4) >>> 2] = value;
	},
	getAnchorX(Module, ptr) {
		return Module.HEAPF32[(ptr + 8) >>> 2];
	},
	setAnchorX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 8) >>> 2] = value;
	},
	getAnchorY(Module, ptr) {
		return Module.HEAPF32[(ptr + 12) >>> 2];
	},
	setAnchorY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 12) >>> 2] = value;
	},
	getAnchorZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 16) >>> 2];
	},
	setAnchorZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 16) >>> 2] = value;
	},
	getHingeAxisX(Module, ptr) {
		return Module.HEAPF32[(ptr + 20) >>> 2];
	},
	setHingeAxisX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 20) >>> 2] = value;
	},
	getHingeAxisY(Module, ptr) {
		return Module.HEAPF32[(ptr + 24) >>> 2];
	},
	setHingeAxisY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 24) >>> 2] = value;
	},
	getHingeAxisZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 28) >>> 2];
	},
	setHingeAxisZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 28) >>> 2] = value;
	},
	getNormalAxisX(Module, ptr) {
		return Module.HEAPF32[(ptr + 32) >>> 2];
	},
	setNormalAxisX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 32) >>> 2] = value;
	},
	getNormalAxisY(Module, ptr) {
		return Module.HEAPF32[(ptr + 36) >>> 2];
	},
	setNormalAxisY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 36) >>> 2] = value;
	},
	getNormalAxisZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 40) >>> 2];
	},
	setNormalAxisZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 40) >>> 2] = value;
	},
	getLimitMin(Module, ptr) {
		return Module.HEAPF32[(ptr + 44) >>> 2];
	},
	setLimitMin(Module, ptr, value) {
		Module.HEAPF32[(ptr + 44) >>> 2] = value;
	},
	getLimitMax(Module, ptr) {
		return Module.HEAPF32[(ptr + 48) >>> 2];
	},
	setLimitMax(Module, ptr, value) {
		Module.HEAPF32[(ptr + 48) >>> 2] = value;
	},
};

export const ConstraintPointOps = {
	getEntityA(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setEntityA(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
	getEntityB(Module, ptr) {
		return Module.HEAPU32[(ptr + 4) >>> 2];
	},
	setEntityB(Module, ptr, value) {
		Module.HEAPU32[(ptr + 4) >>> 2] = value;
	},
	getAnchorX(Module, ptr) {
		return Module.HEAPF32[(ptr + 8) >>> 2];
	},
	setAnchorX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 8) >>> 2] = value;
	},
	getAnchorY(Module, ptr) {
		return Module.HEAPF32[(ptr + 12) >>> 2];
	},
	setAnchorY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 12) >>> 2] = value;
	},
	getAnchorZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 16) >>> 2];
	},
	setAnchorZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 16) >>> 2] = value;
	},
};

export const ConstraintSliderOps = {
	getEntityA(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setEntityA(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
	getEntityB(Module, ptr) {
		return Module.HEAPU32[(ptr + 4) >>> 2];
	},
	setEntityB(Module, ptr, value) {
		Module.HEAPU32[(ptr + 4) >>> 2] = value;
	},
	getSliderAxisX(Module, ptr) {
		return Module.HEAPF32[(ptr + 8) >>> 2];
	},
	setSliderAxisX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 8) >>> 2] = value;
	},
	getSliderAxisY(Module, ptr) {
		return Module.HEAPF32[(ptr + 12) >>> 2];
	},
	setSliderAxisY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 12) >>> 2] = value;
	},
	getSliderAxisZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 16) >>> 2];
	},
	setSliderAxisZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 16) >>> 2] = value;
	},
	getLimitMin(Module, ptr) {
		return Module.HEAPF32[(ptr + 20) >>> 2];
	},
	setLimitMin(Module, ptr, value) {
		Module.HEAPF32[(ptr + 20) >>> 2] = value;
	},
	getLimitMax(Module, ptr) {
		return Module.HEAPF32[(ptr + 24) >>> 2];
	},
	setLimitMax(Module, ptr, value) {
		Module.HEAPF32[(ptr + 24) >>> 2] = value;
	},
};

export const ConstraintSwingTwistOps = {
	getEntityA(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setEntityA(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
	getEntityB(Module, ptr) {
		return Module.HEAPU32[(ptr + 4) >>> 2];
	},
	setEntityB(Module, ptr, value) {
		Module.HEAPU32[(ptr + 4) >>> 2] = value;
	},
	getAnchorX(Module, ptr) {
		return Module.HEAPF32[(ptr + 8) >>> 2];
	},
	setAnchorX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 8) >>> 2] = value;
	},
	getAnchorY(Module, ptr) {
		return Module.HEAPF32[(ptr + 12) >>> 2];
	},
	setAnchorY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 12) >>> 2] = value;
	},
	getAnchorZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 16) >>> 2];
	},
	setAnchorZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 16) >>> 2] = value;
	},
	getTwistAxisX(Module, ptr) {
		return Module.HEAPF32[(ptr + 20) >>> 2];
	},
	setTwistAxisX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 20) >>> 2] = value;
	},
	getTwistAxisY(Module, ptr) {
		return Module.HEAPF32[(ptr + 24) >>> 2];
	},
	setTwistAxisY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 24) >>> 2] = value;
	},
	getTwistAxisZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 28) >>> 2];
	},
	setTwistAxisZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 28) >>> 2] = value;
	},
	getPlaneAxisX(Module, ptr) {
		return Module.HEAPF32[(ptr + 32) >>> 2];
	},
	setPlaneAxisX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 32) >>> 2] = value;
	},
	getPlaneAxisY(Module, ptr) {
		return Module.HEAPF32[(ptr + 36) >>> 2];
	},
	setPlaneAxisY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 36) >>> 2] = value;
	},
	getPlaneAxisZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 40) >>> 2];
	},
	setPlaneAxisZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 40) >>> 2] = value;
	},
	getNormalHalfConeAngle(Module, ptr) {
		return Module.HEAPF32[(ptr + 44) >>> 2];
	},
	setNormalHalfConeAngle(Module, ptr, value) {
		Module.HEAPF32[(ptr + 44) >>> 2] = value;
	},
	getPlaneHalfConeAngle(Module, ptr) {
		return Module.HEAPF32[(ptr + 48) >>> 2];
	},
	setPlaneHalfConeAngle(Module, ptr, value) {
		Module.HEAPF32[(ptr + 48) >>> 2] = value;
	},
	getTwistMinAngle(Module, ptr) {
		return Module.HEAPF32[(ptr + 52) >>> 2];
	},
	setTwistMinAngle(Module, ptr, value) {
		Module.HEAPF32[(ptr + 52) >>> 2] = value;
	},
	getTwistMaxAngle(Module, ptr) {
		return Module.HEAPF32[(ptr + 56) >>> 2];
	},
	setTwistMaxAngle(Module, ptr, value) {
		Module.HEAPF32[(ptr + 56) >>> 2] = value;
	},
};

export const DirectionalLightOps = {
	getDirectionX(Module, ptr) {
		return Module.HEAPF32[(ptr + 0) >>> 2];
	},
	setDirectionX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 0) >>> 2] = value;
	},
	getDirectionY(Module, ptr) {
		return Module.HEAPF32[(ptr + 4) >>> 2];
	},
	setDirectionY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 4) >>> 2] = value;
	},
	getDirectionZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 8) >>> 2];
	},
	setDirectionZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 8) >>> 2] = value;
	},
	getIlluminance(Module, ptr) {
		return Module.HEAPF32[(ptr + 12) >>> 2];
	},
	setIlluminance(Module, ptr, value) {
		Module.HEAPF32[(ptr + 12) >>> 2] = value;
	},
};

export const DirectionalLightSettingsOps = {
	getSunColorX(Module, ptr) {
		return Module.HEAPF32[(ptr + 0) >>> 2];
	},
	setSunColorX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 0) >>> 2] = value;
	},
	getSunColorY(Module, ptr) {
		return Module.HEAPF32[(ptr + 4) >>> 2];
	},
	setSunColorY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 4) >>> 2] = value;
	},
	getSunColorZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 8) >>> 2];
	},
	setSunColorZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 8) >>> 2] = value;
	},
	getAmbientIntensity(Module, ptr) {
		return Module.HEAPF32[(ptr + 12) >>> 2];
	},
	setAmbientIntensity(Module, ptr, value) {
		Module.HEAPF32[(ptr + 12) >>> 2] = value;
	},
};

export const DoNotSerializeOps = {
};

export const EntityMetadataOps = {
	getTitle(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setTitle(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
	getDescription(Module, ptr) {
		return Module.HEAPU32[(ptr + 4) >>> 2];
	},
	setDescription(Module, ptr, value) {
		Module.HEAPU32[(ptr + 4) >>> 2] = value;
	},
};

export const EnvironmentSettingsOps = {
	getSkyCubemapNameHash(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setSkyCubemapNameHash(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
};

export const GizmoOps = {
	getGizmoType(Module, ptr) {
		return Module.HEAPU8[(ptr + 0) >>> 0];
	},
	setGizmoType(Module, ptr, value) {
		Module.HEAPU8[(ptr + 0) >>> 0] = value;
	},
	getSelectedAxes(Module, ptr) {
		return Module.HEAPU8[(ptr + 1) >>> 0];
	},
	setSelectedAxes(Module, ptr, value) {
		Module.HEAPU8[(ptr + 1) >>> 0] = value;
	},
};

export const HierarchyOps = {
	getFirstChild(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setFirstChild(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
	getParent(Module, ptr) {
		return Module.HEAPU32[(ptr + 4) >>> 2];
	},
	setParent(Module, ptr, value) {
		Module.HEAPU32[(ptr + 4) >>> 2] = value;
	},
	getPrevSibling(Module, ptr) {
		return Module.HEAPU32[(ptr + 8) >>> 2];
	},
	setPrevSibling(Module, ptr, value) {
		Module.HEAPU32[(ptr + 8) >>> 2] = value;
	},
	getNextSibling(Module, ptr) {
		return Module.HEAPU32[(ptr + 12) >>> 2];
	},
	setNextSibling(Module, ptr, value) {
		Module.HEAPU32[(ptr + 12) >>> 2] = value;
	},
};

export const MainCameraOps = {
};

export const MeshCollisionOps = {
	getMesh(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setMesh(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
};

export const MeshRendererOps = {
	getMesh(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setMesh(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
	getMaterial(Module, ptr) {
		return Module.HEAPU32[(ptr + 4) >>> 2];
	},
	setMaterial(Module, ptr, value) {
		Module.HEAPU32[(ptr + 4) >>> 2] = value;
	},
	getColorX(Module, ptr) {
		return Module.HEAPU8[ptr + 8];
	},
	setColorX(Module, ptr, value) {
		Module.HEAPU8[ptr + 8] = value;
	},
	getColorY(Module, ptr) {
		return Module.HEAPU8[ptr + 9];
	},
	setColorY(Module, ptr, value) {
		Module.HEAPU8[ptr + 9] = value;
	},
	getColorZ(Module, ptr) {
		return Module.HEAPU8[ptr + 10];
	},
	setColorZ(Module, ptr, value) {
		Module.HEAPU8[ptr + 10] = value;
	},
	getColorW(Module, ptr) {
		return Module.HEAPU8[ptr + 11];
	},
	setColorW(Module, ptr, value) {
		Module.HEAPU8[ptr + 11] = value;
	},
};

export const PostProcessSettingsOps = {
	getBloomIntensity(Module, ptr) {
		return Module.HEAPF32[(ptr + 0) >>> 2];
	},
	setBloomIntensity(Module, ptr, value) {
		Module.HEAPF32[(ptr + 0) >>> 2] = value;
	},
	getBloomSize(Module, ptr) {
		return Module.HEAPF32[(ptr + 4) >>> 2];
	},
	setBloomSize(Module, ptr, value) {
		Module.HEAPF32[(ptr + 4) >>> 2] = value;
	},
	getBloomThreshold(Module, ptr) {
		return Module.HEAPF32[(ptr + 8) >>> 2];
	},
	setBloomThreshold(Module, ptr, value) {
		Module.HEAPF32[(ptr + 8) >>> 2] = value;
	},
	getExposure(Module, ptr) {
		return Module.HEAPF32[(ptr + 12) >>> 2];
	},
	setExposure(Module, ptr, value) {
		Module.HEAPF32[(ptr + 12) >>> 2] = value;
	},
	getVignetteStrength(Module, ptr) {
		return Module.HEAPF32[(ptr + 16) >>> 2];
	},
	setVignetteStrength(Module, ptr, value) {
		Module.HEAPF32[(ptr + 16) >>> 2] = value;
	},
	getVignetteThreshold(Module, ptr) {
		return Module.HEAPF32[(ptr + 20) >>> 2];
	},
	setVignetteThreshold(Module, ptr, value) {
		Module.HEAPF32[(ptr + 20) >>> 2] = value;
	},
	getVignetteColorX(Module, ptr) {
		return Module.HEAPF32[(ptr + 24) >>> 2];
	},
	setVignetteColorX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 24) >>> 2] = value;
	},
	getVignetteColorY(Module, ptr) {
		return Module.HEAPF32[(ptr + 28) >>> 2];
	},
	setVignetteColorY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 28) >>> 2] = value;
	},
	getVignetteColorZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 32) >>> 2];
	},
	setVignetteColorZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 32) >>> 2] = value;
	},
	getVignetteColorW(Module, ptr) {
		return Module.HEAPF32[(ptr + 36) >>> 2];
	},
	setVignetteColorW(Module, ptr, value) {
		Module.HEAPF32[(ptr + 36) >>> 2] = value;
	},
	getBrightness(Module, ptr) {
		return Module.HEAPF32[(ptr + 40) >>> 2];
	},
	setBrightness(Module, ptr, value) {
		Module.HEAPF32[(ptr + 40) >>> 2] = value;
	},
	getContrast(Module, ptr) {
		return Module.HEAPF32[(ptr + 44) >>> 2];
	},
	setContrast(Module, ptr, value) {
		Module.HEAPF32[(ptr + 44) >>> 2] = value;
	},
	getSaturation(Module, ptr) {
		return Module.HEAPF32[(ptr + 48) >>> 2];
	},
	setSaturation(Module, ptr, value) {
		Module.HEAPF32[(ptr + 48) >>> 2] = value;
	},
	getHighlights(Module, ptr) {
		return Module.HEAPF32[(ptr + 52) >>> 2];
	},
	setHighlights(Module, ptr, value) {
		Module.HEAPF32[(ptr + 52) >>> 2] = value;
	},
	getShadows(Module, ptr) {
		return Module.HEAPF32[(ptr + 56) >>> 2];
	},
	setShadows(Module, ptr, value) {
		Module.HEAPF32[(ptr + 56) >>> 2] = value;
	},
	getTintX(Module, ptr) {
		return Module.HEAPF32[(ptr + 60) >>> 2];
	},
	setTintX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 60) >>> 2] = value;
	},
	getTintY(Module, ptr) {
		return Module.HEAPF32[(ptr + 64) >>> 2];
	},
	setTintY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 64) >>> 2] = value;
	},
	getTintZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 68) >>> 2];
	},
	setTintZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 68) >>> 2] = value;
	},
	getTintStrength(Module, ptr) {
		return Module.HEAPF32[(ptr + 72) >>> 2];
	},
	setTintStrength(Module, ptr, value) {
		Module.HEAPF32[(ptr + 72) >>> 2] = value;
	},
};

export const RigidBodyOps = {
	getMotionType(Module, ptr) {
		return Module.HEAPU8[(ptr + 0) >>> 0];
	},
	setMotionType(Module, ptr, value) {
		Module.HEAPU8[(ptr + 0) >>> 0] = value;
	},
	getRestitution(Module, ptr) {
		return Module.HEAPF32[(ptr + 4) >>> 2];
	},
	setRestitution(Module, ptr, value) {
		Module.HEAPF32[(ptr + 4) >>> 2] = value;
	},
	getFriction(Module, ptr) {
		return Module.HEAPF32[(ptr + 8) >>> 2];
	},
	setFriction(Module, ptr, value) {
		Module.HEAPF32[(ptr + 8) >>> 2] = value;
	},
	getLinearDamping(Module, ptr) {
		return Module.HEAPF32[(ptr + 12) >>> 2];
	},
	setLinearDamping(Module, ptr, value) {
		Module.HEAPF32[(ptr + 12) >>> 2] = value;
	},
	getAngularDamping(Module, ptr) {
		return Module.HEAPF32[(ptr + 16) >>> 2];
	},
	setAngularDamping(Module, ptr, value) {
		Module.HEAPF32[(ptr + 16) >>> 2] = value;
	},
};

export const RootOps = {
};

export const SelectedOps = {
	getOutlineType(Module, ptr) {
		return Module.HEAPU8[(ptr + 0) >>> 0];
	},
	setOutlineType(Module, ptr, value) {
		Module.HEAPU8[(ptr + 0) >>> 0] = value;
	},
	getColorX(Module, ptr) {
		return Module.HEAPU8[ptr + 1];
	},
	setColorX(Module, ptr, value) {
		Module.HEAPU8[ptr + 1] = value;
	},
	getColorY(Module, ptr) {
		return Module.HEAPU8[ptr + 2];
	},
	setColorY(Module, ptr, value) {
		Module.HEAPU8[ptr + 2] = value;
	},
	getColorZ(Module, ptr) {
		return Module.HEAPU8[ptr + 3];
	},
	setColorZ(Module, ptr, value) {
		Module.HEAPU8[ptr + 3] = value;
	},
	getColorW(Module, ptr) {
		return Module.HEAPU8[ptr + 4];
	},
	setColorW(Module, ptr, value) {
		Module.HEAPU8[ptr + 4] = value;
	},
};

export const SkeletonAnimationOps = {
	getStateMachine(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setStateMachine(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
	getSkeleton(Module, ptr) {
		return Module.HEAPU32[(ptr + 4) >>> 2];
	},
	setSkeleton(Module, ptr, value) {
		Module.HEAPU32[(ptr + 4) >>> 2] = value;
	},
	getAnimClip(Module, ptr) {
		return Module.HEAPU32[(ptr + 8) >>> 2];
	},
	setAnimClip(Module, ptr, value) {
		Module.HEAPU32[(ptr + 8) >>> 2] = value;
	},
	getActionClip(Module, ptr) {
		return Module.HEAPU32[(ptr + 12) >>> 2];
	},
	setActionClip(Module, ptr, value) {
		Module.HEAPU32[(ptr + 12) >>> 2] = value;
	},
	getRemoveTrajectory(Module, ptr) {
		return Module.HEAPU8[(ptr + 16) >>> 0];
	},
	setRemoveTrajectory(Module, ptr, value) {
		Module.HEAPU8[(ptr + 16) >>> 0] = value;
	},
};

export const SphereCollisionOps = {
	getRadius(Module, ptr) {
		return Module.HEAPF32[(ptr + 0) >>> 2];
	},
	setRadius(Module, ptr, value) {
		Module.HEAPF32[(ptr + 0) >>> 2] = value;
	},
};

export const TextOps = {
	getTextId(Module, ptr) {
		return Module.HEAPU32[(ptr + 0) >>> 2];
	},
	setTextId(Module, ptr, value) {
		Module.HEAPU32[(ptr + 0) >>> 2] = value;
	},
};

export const TransformOps = {
	getPositionX(Module, ptr) {
		return Module.HEAPF32[(ptr + 0) >>> 2];
	},
	setPositionX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 0) >>> 2] = value;
	},
	getPositionY(Module, ptr) {
		return Module.HEAPF32[(ptr + 4) >>> 2];
	},
	setPositionY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 4) >>> 2] = value;
	},
	getPositionZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 8) >>> 2];
	},
	setPositionZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 8) >>> 2] = value;
	},
	getRotationX(Module, ptr) {
		return Module.HEAPF32[(ptr + 12) >>> 2];
	},
	setRotationX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 12) >>> 2] = value;
	},
	getRotationY(Module, ptr) {
		return Module.HEAPF32[(ptr + 16) >>> 2];
	},
	setRotationY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 16) >>> 2] = value;
	},
	getRotationZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 20) >>> 2];
	},
	setRotationZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 20) >>> 2] = value;
	},
	getRotationW(Module, ptr) {
		return Module.HEAPF32[(ptr + 24) >>> 2];
	},
	setRotationW(Module, ptr, value) {
		Module.HEAPF32[(ptr + 24) >>> 2] = value;
	},
	getScaleX(Module, ptr) {
		return Module.HEAPF32[(ptr + 28) >>> 2];
	},
	setScaleX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 28) >>> 2] = value;
	},
	getScaleY(Module, ptr) {
		return Module.HEAPF32[(ptr + 32) >>> 2];
	},
	setScaleY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 32) >>> 2] = value;
	},
	getScaleZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 36) >>> 2];
	},
	setScaleZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 36) >>> 2] = value;
	},
	getDetachedFromParent(Module, ptr) {
		return Module.HEAPU8[(ptr + 40) >>> 0];
	},
	setDetachedFromParent(Module, ptr, value) {
		Module.HEAPU8[(ptr + 40) >>> 0] = value;
	},
};

export const WaterSettingsOps = {
	getEnabled(Module, ptr) {
		return Module.HEAPU8[(ptr + 0) >>> 0];
	},
	setEnabled(Module, ptr, value) {
		Module.HEAPU8[(ptr + 0) >>> 0] = value;
	},
	getY(Module, ptr) {
		return Module.HEAPF32[(ptr + 4) >>> 2];
	},
	setY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 4) >>> 2] = value;
	},
	getAmplitude(Module, ptr) {
		return Module.HEAPF32[(ptr + 8) >>> 2];
	},
	setAmplitude(Module, ptr, value) {
		Module.HEAPF32[(ptr + 8) >>> 2] = value;
	},
	getDirection(Module, ptr) {
		return Module.HEAPF32[(ptr + 12) >>> 2];
	},
	setDirection(Module, ptr, value) {
		Module.HEAPF32[(ptr + 12) >>> 2] = value;
	},
	getSpeed(Module, ptr) {
		return Module.HEAPF32[(ptr + 16) >>> 2];
	},
	setSpeed(Module, ptr, value) {
		Module.HEAPF32[(ptr + 16) >>> 2] = value;
	},
	getAlbedoX(Module, ptr) {
		return Module.HEAPF32[(ptr + 20) >>> 2];
	},
	setAlbedoX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 20) >>> 2] = value;
	},
	getAlbedoY(Module, ptr) {
		return Module.HEAPF32[(ptr + 24) >>> 2];
	},
	setAlbedoY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 24) >>> 2] = value;
	},
	getAlbedoZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 28) >>> 2];
	},
	setAlbedoZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 28) >>> 2] = value;
	},
	getExtinction(Module, ptr) {
		return Module.HEAPF32[(ptr + 32) >>> 2];
	},
	setExtinction(Module, ptr, value) {
		Module.HEAPF32[(ptr + 32) >>> 2] = value;
	},
	getWaveProfile(Module, ptr) {
		return Module.HEAPU32[(ptr + 36) >>> 2];
	},
	setWaveProfile(Module, ptr, value) {
		Module.HEAPU32[(ptr + 36) >>> 2] = value;
	},
	getWaveSize(Module, ptr) {
		return Module.HEAPF32[(ptr + 40) >>> 2];
	},
	setWaveSize(Module, ptr, value) {
		Module.HEAPF32[(ptr + 40) >>> 2] = value;
	},
	getFoamProfile(Module, ptr) {
		return Module.HEAPU32[(ptr + 44) >>> 2];
	},
	setFoamProfile(Module, ptr, value) {
		Module.HEAPU32[(ptr + 44) >>> 2] = value;
	},
	getFoamSize(Module, ptr) {
		return Module.HEAPF32[(ptr + 48) >>> 2];
	},
	setFoamSize(Module, ptr, value) {
		Module.HEAPF32[(ptr + 48) >>> 2] = value;
	},
	getFoamRange(Module, ptr) {
		return Module.HEAPF32[(ptr + 52) >>> 2];
	},
	setFoamRange(Module, ptr, value) {
		Module.HEAPF32[(ptr + 52) >>> 2] = value;
	},
	getFoamAlbedoX(Module, ptr) {
		return Module.HEAPF32[(ptr + 56) >>> 2];
	},
	setFoamAlbedoX(Module, ptr, value) {
		Module.HEAPF32[(ptr + 56) >>> 2] = value;
	},
	getFoamAlbedoY(Module, ptr) {
		return Module.HEAPF32[(ptr + 60) >>> 2];
	},
	setFoamAlbedoY(Module, ptr, value) {
		Module.HEAPF32[(ptr + 60) >>> 2] = value;
	},
	getFoamAlbedoZ(Module, ptr) {
		return Module.HEAPF32[(ptr + 64) >>> 2];
	},
	setFoamAlbedoZ(Module, ptr, value) {
		Module.HEAPF32[(ptr + 64) >>> 2] = value;
	},
	getFoamOpacity(Module, ptr) {
		return Module.HEAPF32[(ptr + 68) >>> 2];
	},
	setFoamOpacity(Module, ptr, value) {
		Module.HEAPF32[(ptr + 68) >>> 2] = value;
	},
	getFoamSpeed(Module, ptr) {
		return Module.HEAPF32[(ptr + 72) >>> 2];
	},
	setFoamSpeed(Module, ptr, value) {
		Module.HEAPF32[(ptr + 72) >>> 2] = value;
	},
	getCausticsProfile(Module, ptr) {
		return Module.HEAPU32[(ptr + 76) >>> 2];
	},
	setCausticsProfile(Module, ptr, value) {
		Module.HEAPU32[(ptr + 76) >>> 2] = value;
	},
	getCausticsSize(Module, ptr) {
		return Module.HEAPF32[(ptr + 80) >>> 2];
	},
	setCausticsSize(Module, ptr, value) {
		Module.HEAPF32[(ptr + 80) >>> 2] = value;
	},
	getCausticsBrightness(Module, ptr) {
		return Module.HEAPF32[(ptr + 84) >>> 2];
	},
	setCausticsBrightness(Module, ptr, value) {
		Module.HEAPF32[(ptr + 84) >>> 2] = value;
	},
};

export const Components = {
	Alive,
	AssetReference,
	BoxCollision,
	Camera,
	CapsuleCollision,
	ConstraintDistance,
	ConstraintFixed,
	ConstraintHinge,
	ConstraintPoint,
	ConstraintSlider,
	ConstraintSwingTwist,
	DirectionalLight,
	DirectionalLightSettings,
	DoNotSerialize,
	EntityMetadata,
	EnvironmentSettings,
	Gizmo,
	Hierarchy,
	MainCamera,
	MeshCollision,
	MeshRenderer,
	PostProcessSettings,
	RigidBody,
	Root,
	Selected,
	SkeletonAnimation,
	SphereCollision,
	Text,
	Transform,
	WaterSettings,
};

export const ComponentOps = {
	Alive: AliveOps,
	AssetReference: AssetReferenceOps,
	BoxCollision: BoxCollisionOps,
	Camera: CameraOps,
	CapsuleCollision: CapsuleCollisionOps,
	ConstraintDistance: ConstraintDistanceOps,
	ConstraintFixed: ConstraintFixedOps,
	ConstraintHinge: ConstraintHingeOps,
	ConstraintPoint: ConstraintPointOps,
	ConstraintSlider: ConstraintSliderOps,
	ConstraintSwingTwist: ConstraintSwingTwistOps,
	DirectionalLight: DirectionalLightOps,
	DirectionalLightSettings: DirectionalLightSettingsOps,
	DoNotSerialize: DoNotSerializeOps,
	EntityMetadata: EntityMetadataOps,
	EnvironmentSettings: EnvironmentSettingsOps,
	Gizmo: GizmoOps,
	Hierarchy: HierarchyOps,
	MainCamera: MainCameraOps,
	MeshCollision: MeshCollisionOps,
	MeshRenderer: MeshRendererOps,
	PostProcessSettings: PostProcessSettingsOps,
	RigidBody: RigidBodyOps,
	Root: RootOps,
	Selected: SelectedOps,
	SkeletonAnimation: SkeletonAnimationOps,
	SphereCollision: SphereCollisionOps,
	Text: TextOps,
	Transform: TransformOps,
	WaterSettings: WaterSettingsOps,
};

export const ComponentById = {
	0: Alive,
	1: AssetReference,
	2: BoxCollision,
	3: Camera,
	4: CapsuleCollision,
	5: ConstraintDistance,
	6: ConstraintFixed,
	7: ConstraintHinge,
	8: ConstraintPoint,
	9: ConstraintSlider,
	10: ConstraintSwingTwist,
	11: DirectionalLight,
	12: DirectionalLightSettings,
	13: DoNotSerialize,
	14: EntityMetadata,
	15: EnvironmentSettings,
	16: Gizmo,
	17: Hierarchy,
	18: MainCamera,
	19: MeshCollision,
	20: MeshRenderer,
	21: PostProcessSettings,
	22: RigidBody,
	23: Root,
	24: Selected,
	25: SkeletonAnimation,
	26: SphereCollision,
	27: Text,
	28: Transform,
	29: WaterSettings,
};

export function registerComponents(Mini) {
	if (!Mini || !Mini.game || typeof Mini.game.registerComponents !== "function")
		throw new Error("Mini.game.registerComponents is not available.");
	return Mini.game.registerComponents(Object.values(Components));
}

const MINI_WEB_ECS_CHUNK_TABLE_FLAG_OPTIONAL = 1 << 1;
const MINI_WEB_ECS_CHUNK_TABLE_FLAG_EXCLUDED = 1 << 2;
const MINI_WEB_ECS_CHUNK_TABLE_FLAG_TAG = 1 << 3;

let _ecsModule = null;

export function bindMiniModule(Module) {
	_ecsModule = Module;
	return _ecsModule;
}

function _resolveGlobalModule() {
	if (typeof globalThis !== "undefined") {
		if (globalThis.__miniModule)
			return globalThis.__miniModule;
		if (globalThis.Module)
			return globalThis.Module;
	}
	return null;
}

function _requireModule() {
	if (!_ecsModule)
		_ecsModule = _resolveGlobalModule();
	if (!_ecsModule)
		throw new Error("Mini WASM module is not bound. Load mini_api.js or call bindMiniModule(Module).");
	return _ecsModule;
}

function _heapDataView(Module) {
	return new DataView(Module.HEAPU8.buffer);
}

function _iterSetBits64(maskLo, maskHi) {
	const bits = [];
	let lo = maskLo >>> 0;
	let hi = maskHi >>> 0;
	while (lo !== 0) {
		const lsb = lo & -lo;
		bits.push(31 - Math.clz32(lsb));
		lo = (lo & (lo - 1)) >>> 0;
	}
	while (hi !== 0) {
		const lsb = hi & -hi;
		bits.push((31 - Math.clz32(lsb)) + 32);
		hi = (hi & (hi - 1)) >>> 0;
	}
	return bits;
}

function _packedIndexFromMask(maskLo, maskHi, bit) {
	let count = 0;
	for (const b of _iterSetBits64(maskLo, maskHi)) {
		if (b >= bit)
			break;
		count++;
	}
	return count;
}

function _maskHasBit(maskLo, maskHi, bit) {
	if (bit < 32)
		return (((maskLo >>> bit) & 1) !== 0);
	return (((maskHi >>> (bit - 32)) & 1) !== 0);
}

function _parseChunk(Module, chunkPtr) {
	const view = _heapDataView(Module);
	const chunk = {
		entityBase: view.getUint32(chunkPtr + MiniWebEcsQueryChunkLayout.OFFSETS.entity_base.bytes, true),
		matchMaskLo: view.getUint32(chunkPtr + MiniWebEcsQueryChunkLayout.OFFSETS.match_mask_lo.bytes, true),
		matchMaskHi: view.getUint32(chunkPtr + MiniWebEcsQueryChunkLayout.OFFSETS.match_mask_hi.bytes, true),
		tableCount: view.getUint32(chunkPtr + MiniWebEcsQueryChunkLayout.OFFSETS.table_count.bytes, true),
		tables: [],
		tableByTypeId: new Map(),
	};

	let tableBasePtr = chunkPtr + MiniWebEcsQueryChunkLayout.OFFSETS.tables.bytes;
	for (let i = 0; i < chunk.tableCount; i++) {
		const table = {
			componentTypeId: view.getUint32(tableBasePtr + MiniWebEcsChunkTableLayout.OFFSETS.component_type_id.bytes, true),
			stride: view.getUint32(tableBasePtr + MiniWebEcsChunkTableLayout.OFFSETS.stride.bytes, true),
			basePtr: view.getUint32(tableBasePtr + MiniWebEcsChunkTableLayout.OFFSETS.base_ptr.bytes, true),
			maskLo: view.getUint32(tableBasePtr + MiniWebEcsChunkTableLayout.OFFSETS.mask_lo.bytes, true),
			maskHi: view.getUint32(tableBasePtr + MiniWebEcsChunkTableLayout.OFFSETS.mask_hi.bytes, true),
			flags: view.getUint32(tableBasePtr + MiniWebEcsChunkTableLayout.OFFSETS.flags.bytes, true),
		};
		table.isOptional = (table.flags & MINI_WEB_ECS_CHUNK_TABLE_FLAG_OPTIONAL) !== 0;
		table.isExcluded = (table.flags & MINI_WEB_ECS_CHUNK_TABLE_FLAG_EXCLUDED) !== 0;
		table.isTag = (table.flags & MINI_WEB_ECS_CHUNK_TABLE_FLAG_TAG) !== 0;
		chunk.tables.push(table);
		chunk.tableByTypeId.set(table.componentTypeId, table);
		tableBasePtr += MiniWebEcsQueryChunkLayout.TABLE_ENTRY_STRIDE_BYTES;
	}

	return chunk;
}

function _findChunkForEntity(chunks, entityId) {
	for (const chunk of chunks) {
		const bit = entityId - chunk.entityBase;
		if (bit < 0 || bit >= 64)
			continue;
		if (_maskHasBit(chunk.matchMaskLo, chunk.matchMaskHi, bit))
			return { chunk, bit };
	}
	return null;
}

function _componentByteOffsetForBit(table, bit) {
	if (table == null)
		return null;
	if (!_maskHasBit(table.maskLo, table.maskHi, bit))
		return null;
	if (table.isTag || table.stride === 0)
		return 0;
	if (table.basePtr === 0)
		return null;
	const packedIndex = _packedIndexFromMask(table.maskLo, table.maskHi, bit);
	return (table.basePtr + (packedIndex * table.stride)) >>> 0;
}

class EcsQuery {
	constructor(sceneHandle, handle, chunkPtr) {
		this._sceneHandle = sceneHandle >>> 0;
		this._handle = handle;
		this._chunkPtr = chunkPtr;
		this._released = false;
		this._visitedChunks = [];
		this._activeChunk = null;
		this._activeEntity = null;
	}

	_releaseInternal() {
		if (this._released)
			return;
		const Module = _requireModule();
		if (this._chunkPtr)
			Module._free(this._chunkPtr);
		Module._mini_web_ecs_query_release(this._handle);
		this._released = true;
	}

	release() {
		this._releaseInternal();
	}

	*entities() {
		if (this._released)
			return;
		const Module = _requireModule();
		while (Module._mini_web_ecs_query_next_chunk(this._handle, this._chunkPtr)) {
			const chunk = _parseChunk(Module, this._chunkPtr);
			this._visitedChunks.push(chunk);
			for (const bit of _iterSetBits64(chunk.matchMaskLo, chunk.matchMaskHi)) {
				const entityId = chunk.entityBase + bit;
				this._activeChunk = chunk;
				this._activeEntity = entityId;
				yield entityId;
			}
		}
	}

	read(Component, entityId = this._activeEntity) {
		if (this._released || entityId == null || !Component)
			return null;
		const typeId = (Component.typeId !== undefined) ? Component.typeId : Component.id;
		if (typeId === undefined)
			return null;

		let location = null;
		if (this._activeChunk) {
			const activeBit = entityId - this._activeChunk.entityBase;
			if (activeBit >= 0 && activeBit < 64 && _maskHasBit(this._activeChunk.matchMaskLo, this._activeChunk.matchMaskHi, activeBit))
				location = { chunk: this._activeChunk, bit: activeBit };
		}
		if (!location)
			location = _findChunkForEntity(this._visitedChunks, entityId);
		if (!location)
			return null;

		const table = location.chunk.tableByTypeId.get(typeId);
		if (!table)
			return null;

		const byteOffset = _componentByteOffsetForBit(table, location.bit);
		if (byteOffset == null)
			return null;

		if (table.isTag || table.stride === 0)
			return {};
		if (Component.byteSize !== undefined && table.stride !== Component.byteSize)
			return null;

		return Component.read(_heapDataView(_requireModule()), byteOffset);
	}

	write(Component, value, entityId = this._activeEntity) {
		if (this._released || entityId == null || !Component)
			return false;
		const typeId = (Component.typeId !== undefined) ? Component.typeId : Component.id;
		if (typeId === undefined)
			return false;

		let location = null;
		if (this._activeChunk) {
			const activeBit = entityId - this._activeChunk.entityBase;
			if (activeBit >= 0 && activeBit < 64 && _maskHasBit(this._activeChunk.matchMaskLo, this._activeChunk.matchMaskHi, activeBit))
				location = { chunk: this._activeChunk, bit: activeBit };
		}
		if (!location)
			location = _findChunkForEntity(this._visitedChunks, entityId);
		if (!location)
			return false;

		const table = location.chunk.tableByTypeId.get(typeId);
		if (!table || table.isTag || table.stride === 0)
			return false;
		if (Component.byteSize !== undefined && table.stride !== Component.byteSize)
			return false;

		const byteOffset = _componentByteOffsetForBit(table, location.bit);
		if (byteOffset == null)
			return false;

		Component.write(_heapDataView(_requireModule()), byteOffset, value);
		return true;
	}
}

class EcsQueryBuilder {
	constructor(sceneHandle) {
		this._sceneHandle = sceneHandle >>> 0;
		this._filters = [];
	}

	with(Component) {
		this._filters.push({ mode: "required", component: Component });
		return this;
	}

	optional(Component) {
		this._filters.push({ mode: "optional", component: Component });
		return this;
	}

	without(Component) {
		this._filters.push({ mode: "excluded", component: Component });
		return this;
	}

	begin() {
		const Module = _requireModule();
		const handle = Module._mini_web_ecs_query_create(this._sceneHandle);
		if (!handle)
			throw new Error("mini_web_ecs_query_create failed");

		for (const filter of this._filters) {
			const typeId = (filter.component && filter.component.typeId !== undefined) ? filter.component.typeId : (filter.component ? filter.component.id : undefined);
			if (typeId === undefined)
				continue;
			let ok = 0;
			if (filter.mode === "required")
				ok = Module._mini_web_ecs_query_add_required(handle, typeId);
			else if (filter.mode === "optional")
				ok = Module._mini_web_ecs_query_add_optional(handle, typeId);
			else
				ok = Module._mini_web_ecs_query_add_excluded(handle, typeId);
			if (!ok) {
				Module._mini_web_ecs_query_release(handle);
				throw new Error("failed to add query filter");
			}
		}

		if (!Module._mini_web_ecs_query_begin(handle)) {
			Module._mini_web_ecs_query_release(handle);
			throw new Error("mini_web_ecs_query_begin failed");
		}

		const chunkPtr = Module._malloc(MiniWebEcsQueryChunkLayout.SIZE_BYTES);
		if (!chunkPtr) {
			Module._mini_web_ecs_query_release(handle);
			throw new Error("failed to allocate query chunk buffer");
		}

		return new EcsQuery(this._sceneHandle, handle, chunkPtr);
	}
}

function _componentTypeId(Component) {
	if (!Component)
		return undefined;
	if (Component.typeId !== undefined)
		return Component.typeId >>> 0;
	if (Component.id !== undefined)
		return Component.id >>> 0;
	return undefined;
}

function _componentByteSize(Component) {
	if (!Component)
		return 0;
	if (Component.byteSize !== undefined)
		return Component.byteSize >>> 0;
	if (Component.size !== undefined)
		return Component.size >>> 0;
	return 0;
}

function _componentName(Component) {
	return (Component && Component.name) ? String(Component.name) : "component";
}

export const ECS = {
	bindModule(Module) {
		return bindMiniModule(Module);
	},

	createEntity(sceneHandle) {
		const Module = _requireModule();
		const entityId = Module._mini_web_ecs_entity_create(sceneHandle >>> 0) >>> 0;
		if (entityId === (0xffffffff >>> 0))
			throw new Error("failed to create entity");
		return entityId;
	},

	query(sceneHandle) {
		return new EcsQueryBuilder(sceneHandle);
	},

	addComponent(sceneHandle, entityId, Component, value = undefined) {
		const Module = _requireModule();
		const typeId = _componentTypeId(Component);
		if (typeId === undefined)
			throw new Error("ECS.addComponent requires a component descriptor with typeId");
		const ptr = Module._mini_web_ecs_table_add(sceneHandle >>> 0, entityId >>> 0, typeId >>> 0) >>> 0;
		const hasComponent = Module._mini_web_ecs_has_component(sceneHandle >>> 0, entityId >>> 0, typeId >>> 0) !== 0;
		if (!hasComponent)
			throw new Error(`failed to add component '${_componentName(Component)}' to entity ${entityId >>> 0}`);
		const byteSize = _componentByteSize(Component);
		if (byteSize === 0) {
			return { ok: true, entityId: entityId >>> 0, componentTypeId: typeId >>> 0, isTag: true, ptr: 0 };
		}
		if (!ptr)
			throw new Error(`component '${_componentName(Component)}' on entity ${entityId >>> 0} has data but returned a null pointer`);
		if (value !== undefined && typeof Component.write !== "function")
			throw new Error(`component '${_componentName(Component)}' does not provide a write() helper`);
		if (value !== undefined)
			Component.write(_heapDataView(Module), ptr, value);
		return { ok: true, entityId: entityId >>> 0, componentTypeId: typeId >>> 0, isTag: false, ptr: ptr >>> 0 };
	},

	getComponentPointer(sceneHandle, entityId, Component) {
		const Module = _requireModule();
		const typeId = _componentTypeId(Component);
		if (typeId === undefined)
			return 0;
		const hasComponent = Module._mini_web_ecs_has_component(sceneHandle >>> 0, entityId >>> 0, typeId >>> 0) !== 0;
		if (!hasComponent)
			return 0;
		if (_componentByteSize(Component) === 0)
			return 0;
		const ptr = Module._mini_web_ecs_table_get(sceneHandle >>> 0, entityId >>> 0, typeId >>> 0) >>> 0;
		if (!ptr)
			throw new Error(`component '${_componentName(Component)}' exists on entity ${entityId >>> 0} but returned a null pointer`);
		return ptr;
	},

	writeComponent(sceneHandle, entityId, Component, value) {
		const Module = _requireModule();
		const typeId = _componentTypeId(Component);
		if (typeId === undefined)
			throw new Error("ECS.writeComponent requires a component descriptor with typeId");
		let ptr = 0;
		if (Module._mini_web_ecs_has_component(sceneHandle >>> 0, entityId >>> 0, typeId >>> 0) !== 0) {
			ptr = this.getComponentPointer(sceneHandle, entityId, Component);
			if (_componentByteSize(Component) === 0)
				return { ok: true, entityId: entityId >>> 0, componentTypeId: typeId >>> 0, isTag: true, ptr: 0 };
			if (typeof Component.write !== "function")
				throw new Error(`component '${_componentName(Component)}' does not provide a write() helper`);
			Component.write(_heapDataView(Module), ptr, value);
			return { ok: true, entityId: entityId >>> 0, componentTypeId: typeId >>> 0, isTag: false, ptr: ptr >>> 0 };
		}
		return this.addComponent(sceneHandle, entityId, Component, value);
	},

	readComponent(sceneHandle, entityId, Component) {
		const typeId = _componentTypeId(Component);
		if (typeId === undefined)
			return null;
		if (!this.has(sceneHandle, entityId, Component))
			return null;
		if (_componentByteSize(Component) === 0)
			return {};
		const ptr = this.getComponentPointer(sceneHandle, entityId, Component);
		if (typeof Component.read !== "function")
			throw new Error(`component '${_componentName(Component)}' does not provide a read() helper`);
		return Component.read(_heapDataView(_requireModule()), ptr);
	},

	has(sceneHandle, entityId, Component) {
		const Module = _requireModule();
		const typeId = _componentTypeId(Component);
		if (typeId === undefined)
			return false;
		return Module._mini_web_ecs_has_component(sceneHandle >>> 0, entityId >>> 0, typeId >>> 0) !== 0;
	},

	removeComponent(sceneHandle, entityId, Component) {
		const Module = _requireModule();
		const typeId = _componentTypeId(Component);
		if (typeId === undefined)
			return false;
		return Module._mini_web_ecs_remove_component(sceneHandle >>> 0, entityId >>> 0, typeId >>> 0) !== 0;
	},

	destroy(sceneHandle, entityId) {
		const Module = _requireModule();
		return Module._mini_web_ecs_entity_destroy(sceneHandle >>> 0, entityId >>> 0) !== 0;
	},

	destroyMany(sceneHandle, entityIds) {
		const Module = _requireModule();
		if (!entityIds || entityIds.length === 0)
			return 0;

		const count = entityIds.length >>> 0;
		const ptr = Module._malloc(count * 4);
		if (!ptr)
			return 0;
		try {
			for (let i = 0; i < count; i++)
				Module.HEAPU32[(ptr >>> 2) + i] = entityIds[i] >>> 0;
			return Module._mini_web_ecs_entity_destroy_many(sceneHandle >>> 0, ptr, count) >>> 0;
		} finally {
			Module._free(ptr);
		}
	},
};

// Example tool: removes "enemy" entities whose movement speed field is > 10.
// EnemyComponent and MovementComponent are passed in so tools can map to project-specific schemas.
export function toolRemoveEnemiesWithSpeedOver10(sceneHandle, EnemyComponent, MovementComponent, speedFieldName = "speed") {
	const q = ECS.query(sceneHandle).with(EnemyComponent).with(MovementComponent).begin();
	const idsToRemove = [];
	try {
		for (const entityId of q.entities()) {
			const movement = q.read(MovementComponent, entityId);
			if (movement && typeof movement[speedFieldName] === "number" && movement[speedFieldName] > 10)
				idsToRemove.push(entityId);
		}
	} finally {
		q.release();
	}
	return ECS.destroyMany(sceneHandle, idsToRemove);
}

// Example tool using excluded query terms: list all entities with Transform but without Selected.
export function toolListTransformWithoutSelected(sceneHandle) {
	const q = ECS.query(sceneHandle).with(Transform).without(Selected).begin();
	const ids = [];
	try {
		for (const entityId of q.entities())
			ids.push(entityId);
	} finally {
		q.release();
	}
	return ids;
}
