// This file is auto-generated by util/generate_components.py
// Do not edit by hand.

export const MINI_WEB_ECS_MAX_QUERY_TABLES = 16;

export const MiniWebEcsChunkTableLayout = {
	SIZE_BYTES: 24,
	SIZE_WORDS: 6,
	OFFSETS: {
		component_type_id: { bytes: 0, words: 0 },
		stride: { bytes: 4, words: 1 },
		base_ptr: { bytes: 8, words: 2 },
		mask_lo: { bytes: 12, words: 3 },
		mask_hi: { bytes: 16, words: 4 },
		flags: { bytes: 20, words: 5 },
	},
};

export const MiniWebEcsQueryChunkLayout = {
	SIZE_BYTES: 400,
	SIZE_WORDS: 100,
	HEADER_SIZE_BYTES: 16,
	HEADER_SIZE_WORDS: 4,
	TABLE_ENTRY_STRIDE_BYTES: MiniWebEcsChunkTableLayout.SIZE_BYTES,
	TABLE_ENTRY_STRIDE_WORDS: MiniWebEcsChunkTableLayout.SIZE_WORDS,
	MAX_TABLE_COUNT: 16,
	OFFSETS: {
		entity_base: { bytes: 0, words: 0 },
		match_mask_lo: { bytes: 4, words: 1 },
		match_mask_hi: { bytes: 8, words: 2 },
		table_count: { bytes: 12, words: 3 },
		tables: { bytes: 16, words: 4 },
	},
};
